#!/bin/bash
# gen.sh — regenerate generated code + CRD manifests.
#
#   gen.sh            regenerate in place (go mod tidy + go generate)
#   gen.sh --check    regenerate into a scratch tree and fail if the
#                     committed crds/ differ — the CI codegen-drift gate
#
# The CRD manifests under crds/ are generated by controller-gen, pinned
# to the sigs.k8s.io/controller-tools version in go.mod (go run resolves
# that exact version). The --check mode is the regression guard for
# Stage 1 of the CRD pipeline (Go type -> crds/): it makes a stale or
# hand-edited crds/ a hard CI failure, so the YAML can never drift from
# core.go or from the pinned controller-gen.
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ "${1:-}" == "--check" ]]; then
  scratch="$(mktemp -d)"
  trap 'rm -rf "$scratch"' EXIT
  cp -R crds "$scratch/crds-committed"

  go mod tidy
  go generate ./...

  if ! diff -ru "$scratch/crds-committed" crds; then
    echo
    echo "ERROR: crds/ is out of sync with the Go types / pinned controller-gen."
    echo "       Run 'bash scripts/gen.sh' and commit the regenerated crds/."
    # Restore the committed crds/ so --check leaves the tree untouched.
    rm -rf crds && mv "$scratch/crds-committed" crds
    exit 1
  fi
  echo "OK: crds/ is in sync with the Go types + pinned controller-gen."
  exit 0
fi

go mod tidy
go generate ./...
