#!/usr/bin/env python3
"""
Snowplow Warmup Matrix Test
============================
Measures backend response time under 4 configurations + an incremental
resource lifecycle scenario, then compares them.

  Scenario A: cache ENABLED  + zero *-clientconfig secrets  (L3 warm, L1 cold)
  Scenario B: cache ENABLED  + clientconfig present         (L3 warm + L1 warm)
  Scenario C: cache DISABLED + zero *-clientconfig secrets  (no cache at all)
  Scenario D: cache DISABLED + clientconfig present         (no cache, secret ignored)
  Scenario E: incremental resource lifecycle with cache ENABLED + clientconfig

Clientconfig secrets are generated by logging in via the authn service
(a login creates {username}-clientconfig in the authn namespace).
"""

import base64
import json
import os
import statistics
import subprocess
import sys
import time
import urllib.error
import urllib.request

# ── Configuration ─────────────────────────────────────────────────────────────
SNOWPLOW = os.environ.get("SNOWPLOW_URL", "http://34.135.50.203:8081")
UI_URL = os.environ.get("UI_URL", "http://34.46.217.105:8080")
AUTHN = os.environ.get("AUTHN_URL", "http://34.136.84.51:8082")
ITERS = int(os.environ.get("ITERS", "20"))
NS = "krateo-system"
BENCH_NS_COUNT = 20
COMP_GVR = "composition.krateo.io"
COMP_VER = "v1-2-2"
COMP_RES = "githubscaffoldingwithcompositionpages"
COMP_KIND = "GithubScaffoldingWithCompositionPage"
COMPDEF_NAME = "github-scaffolding-with-composition-page"

USERS = {
    "admin":      "jl1DDPGMFOWw",
    "cyberjoker": "T8te3k57Nm22",
}

DASHBOARD_PATH = "/call?apiVersion=widgets.templates.krateo.io%2Fv1beta1&resource=pages&name=dashboard-page&namespace=krateo-system"
COMP_LIST_PATH = "/call?apiVersion=templates.krateo.io%2Fv1&resource=restactions&name=compositions-list&namespace=krateo-system"

ENDPOINTS = [
    ("page/dashboard", DASHBOARD_PATH),
    ("page/blueprints",
     "/call?apiVersion=widgets.templates.krateo.io%2Fv1beta1&resource=pages&name=blueprints-page&namespace=krateo-system"),
    ("page/compositions",
     "/call?apiVersion=widgets.templates.krateo.io%2Fv1beta1&resource=pages&name=compositions-page&namespace=krateo-system"),
    ("navmenu/sidebar",
     "/call?apiVersion=widgets.templates.krateo.io%2Fv1beta1&resource=navmenus&name=sidebar-nav-menu&namespace=krateo-system"),
    ("routesloader",
     "/call?apiVersion=widgets.templates.krateo.io%2Fv1beta1&resource=routesloaders&name=routes-loader&namespace=krateo-system"),
    ("restaction/all-routes",
     "/call?apiVersion=templates.krateo.io%2Fv1&resource=restactions&name=all-routes&namespace=krateo-system"),
    ("restaction/comp-list", COMP_LIST_PATH),
]

UI_PAGES = [
    ("ui/dashboard",     "/dashboard"),
    ("ui/compositions",  "/compositions"),
    ("ui/blueprints",    "/blueprints"),
]

# ── Colours ───────────────────────────────────────────────────────────────────
BOLD = "\033[1m"
CYAN = "\033[96m"
GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
DIM = "\033[2m"
RESET = "\033[0m"
SEP = "─" * 120
DSEP = "━" * 120

# ── Helpers ───────────────────────────────────────────────────────────────────

def log(msg):
    ts = time.strftime("%H:%M:%S")
    print(f"  {DIM}[{ts}]{RESET} {msg}", flush=True)


def section(title):
    print(f"\n{BOLD}{CYAN}{SEP}{RESET}")
    print(f"{BOLD}{CYAN}  {title}{RESET}")
    print(f"{BOLD}{CYAN}{SEP}{RESET}")


def login(username, password):
    """Login via authn basic/login.  This also creates {username}-clientconfig."""
    creds = base64.b64encode(f"{username}:{password}".encode()).decode()
    req = urllib.request.Request(
        AUTHN + "/basic/login",
        headers={"Authorization": "Basic " + creds},
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)["accessToken"]


def http_get_ms(path, token, base_url=None, timeout=60):
    url = (base_url or SNOWPLOW) + path
    req = urllib.request.Request(
        url,
        headers={"Authorization": "Bearer " + token},
    )
    t0 = time.perf_counter()
    code = 0
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            r.read()
            code = r.status
    except urllib.error.HTTPError as e:
        code = e.code
    except Exception:
        pass
    return int((time.perf_counter() - t0) * 1000), code


def ui_get_ms(path, token, timeout=60):
    """GET a UI page (HTML) through the frontend.  Passes the JWT as a cookie
    (krateo-token) so the UI proxy can forward authenticated API calls."""
    url = UI_URL + path
    req = urllib.request.Request(url, headers={
        "Authorization": "Bearer " + token,
        "Cookie": f"krateo-token={token}",
    })
    t0 = time.perf_counter()
    code = 0
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            r.read()
            code = r.status
    except urllib.error.HTTPError as e:
        code = e.code
    except Exception:
        pass
    return int((time.perf_counter() - t0) * 1000), code


def pct(data, p):
    s = sorted(data)
    return s[max(0, int(round(p / 100.0 * len(s))) - 1)]


def kubectl(*args, input_data=None):
    proc = subprocess.run(
        ["kubectl"] + list(args),
        input=input_data.encode() if input_data else None,
        capture_output=True,
    )
    return proc.returncode, proc.stdout.decode().strip(), proc.stderr.decode().strip()


def wait_for_snowplow(extra_warmup=0):
    log("Waiting for snowplow health endpoint...")
    for _ in range(90):
        try:
            with urllib.request.urlopen(SNOWPLOW + "/health", timeout=5):
                log("Snowplow healthy")
                if extra_warmup > 0:
                    log(f"Sleeping {extra_warmup}s for L3 warmup to complete...")
                    time.sleep(extra_warmup)
                return True
        except Exception:
            time.sleep(2)
    log("ERROR: snowplow not ready after 180s")
    return False


def wait_for_l1_warmup():
    log("Waiting for L1 warmup to complete (polling logs)...")
    deadline = time.time() + 120
    while time.time() < deadline:
        rc, out, _ = kubectl(
            "logs", "deployment/snowplow", "-n", NS,
            "-c", "snowplow", "--tail=300")
        if "L1 warmup: completed" in out:
            log("L1 warmup completed (found in logs)")
            return True
        if "L1 warmup: skipped" in out or "L1 warmup: no users found" in out:
            log("L1 warmup skipped (no users / no GVRs)")
            return True
        time.sleep(5)
    log("WARNING: L1 warmup completion not detected within 120s")
    return False


# ── Environment manipulation ─────────────────────────────────────────────────

def get_clientconfig_secrets():
    rc, out, _ = kubectl("get", "secrets", "-n", NS, "-o", "name")
    return [s.replace("secret/", "") for s in out.split("\n")
            if s.strip() and "-clientconfig" in s]


def delete_all_clientconfig_secrets():
    secrets = get_clientconfig_secrets()
    for name in secrets:
        kubectl("delete", "secret", name, "-n", NS, "--ignore-not-found")
    log(f"Deleted {len(secrets)} clientconfig secrets: {secrets}")


def generate_clientconfigs():
    """Login as every user — the authn service creates *-clientconfig secrets."""
    log("Generating clientconfig secrets by logging in as each user...")
    for username, password in USERS.items():
        try:
            login(username, password)
            log(f"  {username}-clientconfig generated (login OK)")
        except Exception as e:
            log(f"  WARNING: {username} login failed: {e}")
    time.sleep(2)
    created = get_clientconfig_secrets()
    log(f"Clientconfig secrets now present: {created}")


def disable_cache():
    log("Removing Redis sidecar to disable cache...")
    kubectl("patch", "deployment", "snowplow", "-n", NS,
            "--type=json",
            '-p=[{"op":"remove","path":"/spec/template/spec/initContainers"}]')
    kubectl("rollout", "status", "deployment/snowplow", "-n", NS,
            "--timeout=180s")
    wait_for_snowplow()
    time.sleep(3)
    log("Cache disabled (no Redis)")


def enable_cache():
    log("Restoring Redis sidecar...")
    patch = json.dumps({
        "spec": {"template": {"spec": {"initContainers": [{
            "name": "redis",
            "image": "redis:7-alpine",
            "restartPolicy": "Always",
            "ports": [{"containerPort": 6379}],
            "readinessProbe": {
                "exec": {"command": ["redis-cli", "ping"]},
                "initialDelaySeconds": 2, "periodSeconds": 3,
            },
            "resources": {
                "requests": {"cpu": "50m", "memory": "64Mi"},
                "limits": {"cpu": "200m", "memory": "128Mi"},
            },
        }]}}},
    })
    kubectl("patch", "deployment", "snowplow", "-n", NS,
            "--type=strategic", "-p", patch)
    kubectl("rollout", "status", "deployment/snowplow", "-n", NS,
            "--timeout=180s")
    wait_for_snowplow()
    time.sleep(5)
    log("Cache enabled (Redis sidecar restored)")


def restart_snowplow():
    kubectl("rollout", "restart", "deployment/snowplow", "-n", NS)
    kubectl("rollout", "status", "deployment/snowplow", "-n", NS,
            "--timeout=180s")


# ── Benchmark runner ──────────────────────────────────────────────────────────

def run_scenario(label, cache_on, has_clientconfig):
    """Run one A/B/C/D scenario.  Returns {cold: {...}, warm: {...}}."""
    section(f"Scenario {label}")

    # 1. Set up clientconfig secrets
    if has_clientconfig:
        generate_clientconfigs()
    else:
        delete_all_clientconfig_secrets()

    # 2. Set up cache
    if cache_on:
        enable_cache()
    else:
        disable_cache()

    # 3. Restart to pick up changes
    restart_snowplow()
    if not wait_for_snowplow(extra_warmup=5 if cache_on else 0):
        return None

    # 4. Wait for L1 warmup if applicable
    if cache_on and has_clientconfig:
        wait_for_l1_warmup()

    # 5. Login (this also re-creates clientconfig if has_clientconfig,
    #    but after restart the L1 warmup has already run with the pre-existing secrets)
    log("Logging in as admin...")
    try:
        token = login("admin", USERS["admin"])
        log("JWT acquired")
    except Exception as e:
        log(f"ERROR: login failed: {e}")
        return None

    # 6. Cold latency — backend (direct snowplow)
    log("Measuring cold latency — backend (direct snowplow)...")
    cold = {}
    for ep_label, path in ENDPOINTS:
        ms, code = http_get_ms(path, token)
        cold[ep_label] = ms
        icon = GREEN + "✓" + RESET if code == 200 else RED + "✗" + RESET
        log(f"  {icon} COLD  {ep_label:<25s}  {ms:>5d}ms  HTTP {code}")

    # 7. Cold latency — UI navigation
    log("Measuring cold latency — UI pages...")
    ui_cold = {}
    for ep_label, path in UI_PAGES:
        ms, code = ui_get_ms(path, token)
        ui_cold[ep_label] = ms
        icon = GREEN + "✓" + RESET if 200 <= code < 400 else RED + "✗" + RESET
        log(f"  {icon} COLD  {ep_label:<25s}  {ms:>5d}ms  HTTP {code}")

    # 8. Warm latency — backend
    log(f"Measuring warm latency — backend ({ITERS} iterations)...")
    warm = {}
    for ep_label, path in ENDPOINTS:
        http_get_ms(path, token)
        http_get_ms(path, token)
        latencies = []
        for _ in range(ITERS):
            ms, _ = http_get_ms(path, token)
            latencies.append(ms)
        p50 = pct(latencies, 50)
        p90 = pct(latencies, 90)
        mean = round(statistics.mean(latencies))
        warm[ep_label] = {"p50": p50, "p90": p90, "mean": mean}
        log(f"       WARM  {ep_label:<25s}  p50={p50:>5d}ms  p90={p90:>5d}ms  mean={mean:>5d}ms")

    # 9. Warm latency — UI navigation
    log(f"Measuring warm latency — UI pages ({ITERS} iterations)...")
    ui_warm = {}
    for ep_label, path in UI_PAGES:
        ui_get_ms(path, token)
        ui_get_ms(path, token)
        latencies = []
        for _ in range(ITERS):
            ms, _ = ui_get_ms(path, token)
            latencies.append(ms)
        p50 = pct(latencies, 50)
        p90 = pct(latencies, 90)
        mean = round(statistics.mean(latencies))
        ui_warm[ep_label] = {"p50": p50, "p90": p90, "mean": mean}
        log(f"       WARM  {ep_label:<25s}  p50={p50:>5d}ms  p90={p90:>5d}ms  mean={mean:>5d}ms")

    return {"cold": cold, "warm": warm, "ui_cold": ui_cold, "ui_warm": ui_warm}


# ── Lifecycle scenario (Scenario E) ──────────────────────────────────────────

COMPDEF_YAML = """\
apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: github-scaffolding-with-composition-page
  namespace: bench-ns-01
spec:
  chart:
    repo: github-scaffolding-with-composition-page
    url: https://marketplace.krateo.io
    version: 1.2.2
"""

def composition_yaml(ns, name):
    return f"""\
apiVersion: composition.krateo.io/v1-2-2
kind: GithubScaffoldingWithCompositionPage
metadata:
  name: {name}
  namespace: {ns}
spec:
  argocd:
    namespace: krateo-system
    application:
      project: default
      source:
        path: chart/
      destination:
        server: https://kubernetes.default.svc
        namespace: {name}
      syncEnabled: false
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  app:
    service:
      type: NodePort
      port: 31180
  git:
    unsupportedCapabilities: true
    insecure: true
    fromRepo:
      scmUrl: https://github.com
      org: krateoplatformops-blueprints
      name: github-scaffolding-with-composition-page
      branch: main
      path: skeleton/
      credentials:
        authMethod: generic
        secretRef:
          namespace: krateo-system
          name: github-repo-creds
          key: token
    toRepo:
      scmUrl: https://github.com
      org: krateoplatformops-test
      name: {name}
      branch: main
      path: /
      credentials:
        authMethod: generic
        secretRef:
          namespace: krateo-system
          name: github-repo-creds
          key: token
      private: false
      initialize: true
      deletionPolicy: Delete
      verbose: false
      configurationRef:
        name: repo-config
        namespace: demo-system
"""


def refresh_dashboard(token, label):
    ms_dash, code_dash = http_get_ms(DASHBOARD_PATH, token)
    ms_comp, code_comp = http_get_ms(COMP_LIST_PATH, token)
    ui_dash, ui_dash_code = ui_get_ms("/dashboard", token)
    ui_comp, ui_comp_code = ui_get_ms("/compositions", token)
    d_icon = GREEN + "✓" + RESET if code_dash == 200 else RED + "✗" + RESET
    c_icon = GREEN + "✓" + RESET if code_comp == 200 else RED + "✗" + RESET
    ud_icon = GREEN + "✓" + RESET if 200 <= ui_dash_code < 400 else RED + "✗" + RESET
    uc_icon = GREEN + "✓" + RESET if 200 <= ui_comp_code < 400 else RED + "✗" + RESET
    log(f"  {d_icon} backend: dashboard={ms_dash:>5d}ms  comp-list={ms_comp:>5d}ms   "
        f"{ud_icon} UI: dashboard={ui_dash:>5d}ms  compositions={ui_comp:>5d}ms   [{label}]")
    return {
        "label": label,
        "dashboard_ms": ms_dash, "dashboard_code": code_dash,
        "complist_ms": ms_comp, "complist_code": code_comp,
        "ui_dashboard_ms": ui_dash, "ui_dashboard_code": ui_dash_code,
        "ui_compositions_ms": ui_comp, "ui_compositions_code": ui_comp_code,
    }


def wait_for_compdef_ready(timeout=300):
    log(f"Waiting up to {timeout}s for CompositionDefinition to become Ready...")
    deadline = time.time() + timeout
    while time.time() < deadline:
        rc, out, _ = kubectl(
            "get", "compositiondefinitions.core.krateo.io",
            COMPDEF_NAME, "-n", "bench-ns-01",
            "-o", "jsonpath={.status.conditions[?(@.type=='Ready')].status}")
        if rc == 0 and out.strip() == "True":
            log("CompositionDefinition is Ready")
            return True
        time.sleep(5)
    log("WARNING: CompositionDefinition not Ready within timeout")
    return False


def wait_for_crd_gone(timeout=120):
    log(f"Waiting up to {timeout}s for CRD to be removed...")
    deadline = time.time() + timeout
    while time.time() < deadline:
        rc, _, _ = kubectl("get", "crd",
                           f"{COMP_RES}.{COMP_GVR}", "--no-headers")
        if rc != 0:
            log("CRD removed")
            return True
        time.sleep(5)
    log("WARNING: CRD still present after timeout")
    return False


def run_lifecycle_scenario(token):
    """
    Scenario E — Incremental resource lifecycle with cache ENABLED.

    Phases:
      0. Clean slate (zero compositiondefs, zero bench-ns, zero compositions)
      1. Create first bench namespace
      2. Create the CompositionDefinition (waits for CRD to appear)
      3. Create remaining 19 bench namespaces
      4. Create 20 compositions (one per namespace)
      5. Delete 1 composition
    """
    section("Scenario E — Incremental Resource Lifecycle (cache ENABLED)")
    phases = []
    informer_settle = 10

    # ── Phase 0: clean slate ──────────────────────────────────────────────────
    log("Phase 0: establishing clean slate...")

    rc, out, _ = kubectl("get", f"{COMP_RES}.{COMP_GVR}", "-A",
                         "--no-headers", "-o",
                         "custom-columns=NS:.metadata.namespace,NAME:.metadata.name")
    if rc == 0 and out.strip():
        for line in out.strip().split("\n"):
            parts = line.split()
            if len(parts) == 2:
                kubectl("delete", f"{COMP_RES}.{COMP_GVR}", parts[1],
                        "-n", parts[0], "--ignore-not-found", "--wait=false")
        log("Composition delete requests sent, waiting 30s for finalizers...")
        time.sleep(30)

    kubectl("delete", "compositiondefinitions.core.krateo.io",
            COMPDEF_NAME, "-n", "bench-ns-01",
            "--ignore-not-found", "--wait=false")
    log("CompositionDefinition delete requested")
    time.sleep(10)
    wait_for_crd_gone(timeout=180)

    for i in range(1, BENCH_NS_COUNT + 1):
        kubectl("delete", "ns", f"bench-ns-{i:02d}", "--ignore-not-found",
                "--wait=false")
    log(f"Deleted {BENCH_NS_COUNT} bench namespaces (async)")
    log("Waiting 30s for namespace cleanup...")
    time.sleep(30)

    rc, out, _ = kubectl("get", "ns", "-o", "name")
    remaining = [l for l in out.split("\n") if "bench-ns-" in l]
    if remaining:
        log(f"Still {len(remaining)} bench namespaces, waiting 60s more...")
        time.sleep(60)

    time.sleep(informer_settle)
    phases.append(refresh_dashboard(token, "Phase 0: clean slate"))

    # ── Phase 1: create first bench namespace ─────────────────────────────────
    log("Phase 1: creating bench-ns-01...")
    kubectl("create", "ns", "bench-ns-01")
    time.sleep(informer_settle)
    phases.append(refresh_dashboard(token, "Phase 1: +1 namespace"))

    # ── Phase 2: create CompositionDefinition ─────────────────────────────────
    log("Phase 2: creating CompositionDefinition...")
    kubectl("apply", "-f", "-", input_data=COMPDEF_YAML)
    wait_for_compdef_ready(timeout=300)
    time.sleep(informer_settle)
    phases.append(refresh_dashboard(token, "Phase 2: +compdef"))

    # ── Phase 3: create remaining 19 bench namespaces ─────────────────────────
    log(f"Phase 3: creating bench-ns-02 through bench-ns-{BENCH_NS_COUNT:02d}...")
    for i in range(2, BENCH_NS_COUNT + 1):
        kubectl("create", "ns", f"bench-ns-{i:02d}")
    time.sleep(informer_settle)
    phases.append(refresh_dashboard(token, f"Phase 3: +{BENCH_NS_COUNT - 1} namespaces"))

    # ── Phase 4: create 20 compositions ───────────────────────────────────────
    log(f"Phase 4: creating {BENCH_NS_COUNT} compositions...")
    for i in range(1, BENCH_NS_COUNT + 1):
        ns = f"bench-ns-{i:02d}"
        name = f"bench-app-{i:02d}"
        kubectl("apply", "-f", "-", input_data=composition_yaml(ns, name))
    log("All composition apply requests sent, waiting 30s for reconcile...")
    time.sleep(30)
    phases.append(refresh_dashboard(token, f"Phase 4: +{BENCH_NS_COUNT} compositions"))

    # ── Phase 5: delete 1 composition ─────────────────────────────────────────
    log("Phase 5: deleting bench-app-20 in bench-ns-20...")
    kubectl("delete", f"{COMP_RES}.{COMP_GVR}", "bench-app-20",
            "-n", "bench-ns-20", "--ignore-not-found", "--wait=false")
    log("Waiting 15s for informer DELETE event...")
    time.sleep(15)
    phases.append(refresh_dashboard(token, "Phase 5: -1 composition"))

    return phases


# ── Reports ───────────────────────────────────────────────────────────────────

def _print_latency_table(scenarios, labels, key, endpoints, title, stat_key=None):
    """Generic helper to print cold or warm latency comparison tables."""
    print(f"\n  {BOLD}{title}{RESET}\n")
    is_warm = stat_key is not None
    header = f"  {'Endpoint':<25s}"
    for lbl in labels:
        col = lbl + "·" + stat_key if is_warm else lbl
        header += f"  {col:>8s}"
    header += f"  {'B vs A':>8s}  {'A vs C':>8s}  {'B vs C':>8s}"
    print(header)
    print(f"  {SEP}")

    totals = {lbl: 0 for lbl in labels}
    counts = {lbl: 0 for lbl in labels}
    for ep_label, _ in endpoints:
        row = f"  {ep_label:<25s}"
        vals = {}
        for lbl in labels:
            s = scenarios.get(lbl)
            if s and ep_label in s.get(key, {}):
                v = s[key][ep_label] if not is_warm else s[key][ep_label][stat_key]
                vals[lbl] = v
                totals[lbl] += s[key][ep_label]["mean"] if is_warm else v
                counts[lbl] += 1
                row += f"  {v:>6d}ms"
            else:
                row += f"  {'N/A':>8s}"
        for num, den in [("A", "B"), ("C", "A"), ("C", "B")]:
            if num in vals and den in vals and vals[den] > 0:
                ratio = vals[num] / vals[den]
                color = GREEN if ratio > 1.5 else (YELLOW if ratio > 1.0 else RED)
                row += f"  {color}{ratio:>6.1f}x{RESET}"
            else:
                row += f"  {'N/A':>8s}"
        print(row)

    print(f"  {SEP}")
    avg_label = "AVERAGE (mean)" if is_warm else "AVERAGE"
    avg_row = f"  {avg_label:<25s}"
    avgs = {}
    for lbl in labels:
        if counts[lbl] > 0:
            avg = totals[lbl] // counts[lbl]
            avgs[lbl] = avg
            avg_row += f"  {avg:>6d}ms"
        else:
            avg_row += f"  {'N/A':>8s}"
    for num, den in [("A", "B"), ("C", "A"), ("C", "B")]:
        if num in avgs and den in avgs and avgs[den] > 0:
            ratio = avgs[num] / avgs[den]
            color = GREEN if ratio > 1.5 else (YELLOW if ratio > 1.0 else RED)
            avg_row += f"  {color}{ratio:>6.1f}x{RESET}"
        else:
            avg_row += f"  {'N/A':>8s}"
    print(avg_row)


def print_comparison(scenarios):
    section("COMPARISON REPORT — BACKEND (direct snowplow)")

    labels = ["A", "B", "C", "D"]
    desc = {
        "A": "cache ON  + NO clientconfig",
        "B": "cache ON  + clientconfig",
        "C": "cache OFF + NO clientconfig",
        "D": "cache OFF + clientconfig",
    }

    _print_latency_table(scenarios, labels, "cold", ENDPOINTS,
                         "COLD LATENCY — backend (first request after restart, ms)")
    _print_latency_table(scenarios, labels, "warm", ENDPOINTS,
                         f"WARM LATENCY — backend (steady-state p50, {ITERS} iters, ms)",
                         stat_key="p50")

    # ── UI navigation tables ─────────────────────────────────────────────────
    section("COMPARISON REPORT — UI NAVIGATION")
    _print_latency_table(scenarios, labels, "ui_cold", UI_PAGES,
                         "COLD LATENCY — UI pages (first load after restart, ms)")
    _print_latency_table(scenarios, labels, "ui_warm", UI_PAGES,
                         f"WARM LATENCY — UI pages (steady-state p50, {ITERS} iters, ms)",
                         stat_key="p50")

    # ── Analysis ──────────────────────────────────────────────────────────────
    section("ANALYSIS & FINDINGS")
    findings = []

    a_cold = scenarios.get("A", {}).get("cold", {})
    b_cold = scenarios.get("B", {}).get("cold", {})
    if a_cold and b_cold:
        a_t = sum(a_cold.values()); b_t = sum(b_cold.values())
        if b_t > 0:
            r = a_t / b_t
            if r > 2.0:
                findings.append((GREEN, f"[backend] L1 warmup delivers {r:.1f}x cold-start speedup (A={a_t}ms vs B={b_t}ms)"))
            elif r > 1.2:
                findings.append((YELLOW, f"[backend] L1 warmup delivers modest {r:.1f}x cold-start speedup (A={a_t}ms vs B={b_t}ms)"))
            else:
                findings.append((RED, f"[backend] L1 warmup shows NO cold-start improvement ({r:.1f}x) — investigate"))

    a_warm = scenarios.get("A", {}).get("warm", {})
    c_warm = scenarios.get("C", {}).get("warm", {})
    if a_warm and c_warm:
        a_a = sum(v["mean"] for v in a_warm.values()) / max(len(a_warm), 1)
        c_a = sum(v["mean"] for v in c_warm.values()) / max(len(c_warm), 1)
        if a_a > 0:
            r = c_a / a_a
            if r > 1.5:
                findings.append((GREEN, f"[backend] Cache delivers {r:.1f}x warm-latency speedup (A={a_a:.0f}ms vs C={c_a:.0f}ms)"))
            else:
                findings.append((RED, f"[backend] Cache shows minimal warm-latency improvement ({r:.1f}x) — investigate"))

    c_w = scenarios.get("C", {}).get("warm", {})
    d_w = scenarios.get("D", {}).get("warm", {})
    if c_w and d_w:
        c_a = sum(v["mean"] for v in c_w.values()) / max(len(c_w), 1)
        d_a = sum(v["mean"] for v in d_w.values()) / max(len(d_w), 1)
        diff = abs(c_a - d_a) / max(c_a, 1) * 100
        if diff < 15:
            findings.append((GREEN, f"[backend] clientconfig has no impact without cache (C={c_a:.0f}ms vs D={d_a:.0f}ms, Δ={diff:.0f}%)"))
        else:
            findings.append((YELLOW, f"[backend] clientconfig affects latency without cache (Δ={diff:.0f}%) — investigate"))

    b_warm = scenarios.get("B", {}).get("warm", {})
    if a_warm and b_warm:
        a_a = sum(v["mean"] for v in a_warm.values()) / max(len(a_warm), 1)
        b_a = sum(v["mean"] for v in b_warm.values()) / max(len(b_warm), 1)
        diff = abs(a_a - b_a) / max(a_a, 1) * 100
        if diff < 20:
            findings.append((GREEN, f"[backend] Warm latencies similar A vs B (A={a_a:.0f}ms vs B={b_a:.0f}ms, Δ={diff:.0f}%)"))
        else:
            findings.append((YELLOW, f"[backend] Warm latencies differ A vs B (A={a_a:.0f}ms vs B={b_a:.0f}ms, Δ={diff:.0f}%) — investigate"))

    if a_warm and c_warm:
        regressions = []
        for ep_label, _ in ENDPOINTS:
            a_p = a_warm.get(ep_label, {}).get("p50", 0)
            c_p = c_warm.get(ep_label, {}).get("p50", 0)
            if a_p > 0 and c_p > 0 and a_p > c_p * 1.1:
                regressions.append(f"{ep_label} (cached={a_p}ms > nocache={c_p}ms)")
        if regressions:
            findings.append((RED, "[backend] REGRESSION: Cache SLOWER than no-cache for: " + ", ".join(regressions)))
        else:
            findings.append((GREEN, "[backend] No regressions: cache is faster or equal for all endpoints"))

    if b_cold:
        slow = [(ep, ms) for ep, ms in b_cold.items() if ms > 500]
        if slow:
            findings.append((YELLOW, f"[backend] Cold > 500ms even with L1 warmup: {', '.join(f'{e}={m}ms' for e,m in slow)}"))
        else:
            findings.append((GREEN, "[backend] All cold-start endpoints < 500ms with L1 warmup"))

    # UI-specific analysis
    a_ui_warm = scenarios.get("A", {}).get("ui_warm", {})
    b_ui_warm = scenarios.get("B", {}).get("ui_warm", {})
    c_ui_warm = scenarios.get("C", {}).get("ui_warm", {})
    if a_ui_warm and c_ui_warm:
        a_a = sum(v["mean"] for v in a_ui_warm.values()) / max(len(a_ui_warm), 1)
        c_a = sum(v["mean"] for v in c_ui_warm.values()) / max(len(c_ui_warm), 1)
        if a_a > 0:
            r = c_a / a_a
            if r > 1.3:
                findings.append((GREEN, f"[UI] Cache delivers {r:.1f}x UI navigation speedup (A={a_a:.0f}ms vs C={c_a:.0f}ms)"))
            else:
                findings.append((YELLOW, f"[UI] Cache shows limited UI navigation speedup ({r:.1f}x) — UI overhead dominates"))

    if b_ui_warm and a_ui_warm:
        for ep_label, _ in UI_PAGES:
            bv = b_ui_warm.get(ep_label, {}).get("p50", 0)
            av = a_ui_warm.get(ep_label, {}).get("p50", 0)
            if bv > 0 and av > 0:
                overhead = bv - av
                if overhead > 200:
                    findings.append((YELLOW, f"[UI] {ep_label}: L1 warmup saves only {av - bv}ms on UI side (B={bv}ms vs A={av}ms)"))

    # Compare UI overhead vs backend
    if b_warm and b_ui_warm:
        dash_backend = b_warm.get("page/dashboard", {}).get("p50", 0)
        dash_ui = b_ui_warm.get("ui/dashboard", {}).get("p50", 0)
        if dash_backend > 0 and dash_ui > 0:
            overhead_ms = dash_ui - dash_backend
            findings.append((CYAN, f"[UI] UI proxy overhead for dashboard: {overhead_ms:+d}ms (UI={dash_ui}ms vs backend={dash_backend}ms)"))

    print()
    for color, finding in findings:
        icon = "✓" if color == GREEN else ("⚠" if color == YELLOW else ("→" if color == CYAN else "✗"))
        print(f"  {color}{icon}{RESET} {finding}")
    print()

    print(f"  {BOLD}SCENARIO SUMMARY{RESET}")
    print(f"  {SEP}")
    for lbl in labels:
        s = scenarios.get(lbl)
        if not s:
            print(f"  {lbl}: {desc[lbl]:<40s}  SKIPPED"); continue
        ca = sum(s["cold"].values()) // max(len(s["cold"]), 1)
        wa = sum(v["mean"] for v in s["warm"].values()) // max(len(s["warm"]), 1)
        ui_ca = sum(s.get("ui_cold", {}).values()) // max(len(s.get("ui_cold", {})), 1) if s.get("ui_cold") else 0
        ui_wa = sum(v["mean"] for v in s.get("ui_warm", {}).values()) // max(len(s.get("ui_warm", {})), 1) if s.get("ui_warm") else 0
        print(f"  {lbl}: {desc[lbl]:<40s}  backend cold={ca:>5d}ms warm={wa:>5d}ms  |  UI cold={ui_ca:>5d}ms warm={ui_wa:>5d}ms")
    print(f"  {SEP}\n")


def print_lifecycle_report(phases):
    section("LIFECYCLE SCENARIO REPORT (Scenario E)")

    print(f"\n  {BOLD}{'Phase':<40s}  {'backend':>22s}  │  {'UI navigation':>22s}{RESET}")
    print(f"  {BOLD}{'':<40s}  {'dashboard':>10s} {'comp-list':>10s}  │  {'dashboard':>10s} {'comps':>10s}{RESET}")
    print(f"  {SEP}")
    for p in phases:
        dc = GREEN if p["dashboard_code"] == 200 else RED
        cc = GREEN if p["complist_code"] == 200 else RED
        udc = GREEN if p.get("ui_dashboard_code", 0) in range(200, 400) else RED
        ucc = GREEN if p.get("ui_compositions_code", 0) in range(200, 400) else RED
        ui_d = p.get("ui_dashboard_ms", 0)
        ui_c = p.get("ui_compositions_ms", 0)
        print(f"  {p['label']:<40s}  "
              f"{dc}{p['dashboard_ms']:>8d}ms{RESET} "
              f"{cc}{p['complist_ms']:>8d}ms{RESET}  │  "
              f"{udc}{ui_d:>8d}ms{RESET} "
              f"{ucc}{ui_c:>8d}ms{RESET}")
    print(f"  {SEP}")

    print(f"\n  {BOLD}LIFECYCLE ANALYSIS{RESET}\n")
    findings = []

    if len(phases) >= 6:
        all_ok = all(p["dashboard_code"] == 200 for p in phases)
        if all_ok:
            findings.append((GREEN, "[backend] Dashboard returned HTTP 200 in all phases"))
        else:
            bad = [p["label"] for p in phases if p["dashboard_code"] != 200]
            findings.append((RED, f"[backend] Dashboard failed in: {', '.join(bad)}"))

        p0_d, p4_d, p5_d = phases[0]["dashboard_ms"], phases[4]["dashboard_ms"], phases[5]["dashboard_ms"]
        findings.append((CYAN, f"[backend] Clean slate → {p0_d}ms,  after 20 compositions → {p4_d}ms"))

        if p5_d < p4_d * 2:
            findings.append((GREEN, f"[backend] Dashboard responsive after deletion ({p5_d}ms vs {p4_d}ms)"))
        else:
            findings.append((YELLOW, f"[backend] Dashboard slower after deletion ({p5_d}ms vs {p4_d}ms) — cache invalidation may be slow"))

        dash_times = [p["dashboard_ms"] for p in phases]
        mx = max(dash_times)
        if mx < 5000:
            findings.append((GREEN, f"[backend] Dashboard stayed under 5s across all phases (max={mx}ms)"))
        elif mx < 10000:
            findings.append((YELLOW, f"[backend] Dashboard peaked at {mx}ms — acceptable but room for improvement"))
        else:
            findings.append((RED, f"[backend] Dashboard peaked at {mx}ms — too slow"))

        # UI lifecycle analysis
        ui_dash_times = [p.get("ui_dashboard_ms", 0) for p in phases]
        if any(t > 0 for t in ui_dash_times):
            ui_mx = max(ui_dash_times)
            if ui_mx < 5000:
                findings.append((GREEN, f"[UI] Dashboard page stayed under 5s across all phases (max={ui_mx}ms)"))
            elif ui_mx < 10000:
                findings.append((YELLOW, f"[UI] Dashboard page peaked at {ui_mx}ms — acceptable but room for improvement"))
            else:
                findings.append((RED, f"[UI] Dashboard page peaked at {ui_mx}ms — too slow"))

            avg_overhead = sum(
                p.get("ui_dashboard_ms", 0) - p["dashboard_ms"]
                for p in phases if p.get("ui_dashboard_ms", 0) > 0
            ) // max(sum(1 for p in phases if p.get("ui_dashboard_ms", 0) > 0), 1)
            findings.append((CYAN, f"[UI] Average UI overhead vs backend for dashboard: {avg_overhead:+d}ms"))

    print()
    for color, finding in findings:
        icon = "✓" if color == GREEN else ("⚠" if color == YELLOW else ("→" if color == CYAN else "✗"))
        print(f"  {color}{icon}{RESET} {finding}")
    print()


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print(f"\n{BOLD}{DSEP}{RESET}")
    print(f"{BOLD}  Snowplow Warmup Matrix Test{RESET}")
    print(f"  Snowplow  : {SNOWPLOW}")
    print(f"  UI        : {UI_URL}")
    print(f"  Authn     : {AUTHN}")
    print(f"  Users     : {', '.join(USERS.keys())}")
    print(f"  Iterations: {ITERS}")
    print(f"{BOLD}{DSEP}{RESET}\n")

    scenarios = {}
    lifecycle_phases = None
    try:
        # ── Scenario A: cache ON + NO clientconfig ────────────────────────────
        scenarios["A"] = run_scenario(
            "A — cache ENABLED + NO clientconfig (L3 warm, L1 cold)",
            cache_on=True, has_clientconfig=False)

        # ── Scenario B: cache ON + clientconfig ───────────────────────────────
        scenarios["B"] = run_scenario(
            "B — cache ENABLED + clientconfig (L3 + L1 warm)",
            cache_on=True, has_clientconfig=True)

        # ── Scenario C: cache OFF + NO clientconfig ───────────────────────────
        scenarios["C"] = run_scenario(
            "C — cache DISABLED + NO clientconfig (no cache)",
            cache_on=False, has_clientconfig=False)

        # ── Scenario D: cache OFF + clientconfig ──────────────────────────────
        scenarios["D"] = run_scenario(
            "D — cache DISABLED + clientconfig (no cache, secret ignored)",
            cache_on=False, has_clientconfig=True)

        # ── Scenario E: lifecycle with cache ENABLED ──────────────────────────
        generate_clientconfigs()
        enable_cache()
        restart_snowplow()
        wait_for_snowplow(extra_warmup=5)
        wait_for_l1_warmup()
        e_token = login("admin", USERS["admin"])
        log("JWT acquired for lifecycle test")
        lifecycle_phases = run_lifecycle_scenario(e_token)

    finally:
        # ── Restore original state ────────────────────────────────────────────
        section("RESTORING ORIGINAL STATE")
        generate_clientconfigs()
        enable_cache()
        restart_snowplow()
        wait_for_snowplow(extra_warmup=5)
        wait_for_l1_warmup()
        log("Original state restored")

    valid = {k: v for k, v in scenarios.items() if v is not None}
    if valid:
        print_comparison(valid)

    if lifecycle_phases:
        print_lifecycle_report(lifecycle_phases)


if __name__ == "__main__":
    main()
